# Generated by Django 4.0.4 on 2022-05-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_newsletterreceipients_newsletterrecipients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterRecipients',
            new_name='NewsletterRecipient',
        ),
    ]
